### ISSUE TITLE
🚩 ROADMAP v2.1

### ISSUE THREAD

**Issue by Gorzas** [Gorzas/spotify-playlist#2]
Even when this library is for personal use, even with a public code, I'd like to have a personal roadmap of improvements in case I have time to do them. They could be helpful for learning and make the code easier to read.

🚩 v2.1

- [ ] add linter
- [ ] add a testing suite
- [ ] refactor the code and adapt to a more modern JavaScript syntax (i.e. use `let` or `const` instead of `var`).
- [ ] migrate the code to TypeScript (I don't have expertise in TypeScript, so this could be a nice first one to train myself)
